THRESH = 49
UTMS = ['booking-rnc-be',
 'booking-rnc-a',
 'booking-rnc-f',
 'booking-rnc-s',
 'booking-amb-rnc',
 'booking-rnc-g',
 'jscs-instant-book',
 'booking-c2c-be',
 'booking-c2c-a',
 'booking-c2c-f',
 'booking-c2c-s',
 'booking-amb-c2c',
 'jscs-instant-book',
 'jscs-instant-book',
 'booking-ovsl-be',
 'booking-ovsl-a',
 'booking-ovsl-f',
 'booking-ovsl-s',
 'jscs-instant-book',
 'booking-be',
 'booking-pathway',
 'booking-funnel',
 'booking-misc']
AMOUNT = "7400"
